[uber-internal] [pinotSetup] Setting applyLogicalTypes in AvroRecordExtractor to false
Summary:
The avro version pulled at runtime in Fievel is both 1.7.4 and 1.8.2-UBER, and the error started happening while writing segments:
```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.pinot.plugin.inputformat.avro.AvroSchemaUtil at org.apache.pinot.plugin.inputformat.avro.AvroRecordExtractor.extract(AvroRecordExtractor.java:78) at org.apache.pinot.plugin.inputformat.avro.AvroRecordExtractor.extract(AvroRecordExtractor.java:39) at com.uber.uPinot.decoder.HeatpipeKafkaMessageDecoderV3.decode(HeatpipeKafkaMessageDecoderV3.java:66) at com.uber.uPinot.decoder.HeatpipeKafkaMessageDecoderBase.decode(HeatpipeKafkaMessageDecoderBase.java:217) at com.uber.uPinot.decoder.HeatpipeKafkaMessageDecoderBase.decode(HeatpipeKafkaMessageDecoderBase.java:44) at org.apache.pinot.spi.stream.StreamDataDecoderImpl.decode(StreamDataDecoderImpl.java:55) at org.apache.pinot.core.data.manager.realtime.RealtimeSegmentDataManager.processStreamEvents(RealtimeSegmentDataManager.java:624) at org.apache.pinot.core.data.manager.realtime.RealtimeSegmentDataManager.consumeLoop(RealtimeSegmentDataManager.java:511) at org.apache.pinot.core.data.manager.realtime.RealtimeSegmentDataManager$PartitionConsumer.run(RealtimeSegmentDataManager.java:806) at java.base/java.lang.Thread.run(Thread.java:840) Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/avro/data/TimeConversions$TimeMillisConversion [in thread "otp_events__0__427__20250808T0640Z"] at org.apache.pinot.plugin.inputformat.avro.AvroSchemaUtil.<clinit>(AvroSchemaUtil.java:56) ... 10 common frames omitted
```
This is because the pinot-avro plugin, which uses the `org/apache/avro/data/TimeConversions` class introduced in Avro 1.8.2-UBER, enables logical types support by default. This diff reverts this.

1.4 ref: https://code.uberinternal.com/rDAPINJM8998d68e48053a001628f7b34b61faea78697026

Will be merged on `early-release-1.5.x`.

Test Plan: Test details here: https://docs.google.com/document/d/1TNKjp64DpUTyv70pDuQ-QZlYSMyHX6JUwNnvV_aOCNI/edit?tab=t.diddsvxomfia

Reviewers: #ldap_rta-group, ureview, xuanyili, tarunm

Reviewed By: #ldap_rta-group, tarunm

Subscribers: xuanyili

Tags: #has_java

JIRA Issues: EVA-13036

Differential Revision: https://code.uberinternal.com/D21639635